# Generated by Django 3.1.1 on 2020-09-02 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
